- name: Setup my workstation
  hosts: localhost
  become: no
  vars_files:
    - ./vars/vars.yml
  handlers:
    - name: restart vscode
      command: killall Code
      ignore_errors: yes
      
    - name: Update Homebrew
      become: no
      homebrew:
        update_cache: yes

  tasks:
    - name: Install Homebrew
      include_tasks: ./tasks/install_brew.yml
    
    - name: Install git
      include_tasks: ./tasks/install_git.yml

    - name: Install dev tools
      include_tasks: ./tasks/install_dev_tools.yml

    - name: Install fnm
      include_tasks: ./tasks/install_fnm.yml

    - name: Install node global packages
      include_tasks: ./tasks/node_packages.yml

    - name: Install and setup VS Code
      include_tasks: ./tasks/Install_vs_code.yml

    - name: Install infra tools
      include_tasks: ./tasks/install_infra_tools.yml
   

        
