- name: Check if Homebrew is installed
  stat:
    path: /usr/local/bin/brew
  register: brew_installed

- name: Install Homebrew
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: not brew_installed.stat.exists
