- name: Install fnm
  homebrew:
    name: fnm
    state: present

- name: Install Node versions
  shell: fnm install {{ item }}
  loop: "{{ node_versions }}"
  environment:
    PATH: "{{ ansible_env.HOME }}/.fnm:{{ ansible_env.PATH }}"

- name: Set default Node versions
  shell: fnm default {{ node_versions[0] }}
  environment:
    PATH: "{{ ansible_env.HOME }}/.fnm:{{ ansible_env.PATH }}"

- name: Add fnm to the PATH
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bash_profile"
    line: 'export PATH="$HOME/.fnm:$PATH"'
    state: present
    create: yes
    insertafter: EOF
    backup: yes
