- name: Install fnm
  homebrew:
    name: fnm
    state: present

- name: Add fnm to the PATH
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bash_profile"
    line: "{{ item }}"
    state: present
    create: yes
    insertafter: EOF
    backup: yes
  loop:
    - 'export PATH="$HOME/.fnm:$PATH"'
    - 'eval "$(fnm env)"'

- name: Source .bash_profile
  shell: source {{ ansible_env.HOME }}/.bash_profile
  args:
    executable: /bin/bash

- name: Install Node versions
  shell: fnm install {{ item }}
  loop: "{{ node_versions }}"

- name: Set default Node versions
  shell: fnm default {{ node_versions[0] }}
