- name: Install Docker
  shell: |
    
  args:
    executable: /bin/bash

- name: Install Docker tools
   shell: {{ item }}
   loop:
    - docker-ce
    - docker-ce-cli 
    - containerd.io 
    - docker-buildx-plugin 
    - docker-compose-plugin

